name: Nightlies

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # prep the environment
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.407"

      # publish and archive the different executables
      - name: Build executables
        run: ./BuildScripts/BuildAll.ps1

      # publish artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Windows AMD64
          path: Releases/win-x64-slim.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Windows ARM64
          path: Releases/win-arm64-slim.zip
