name: Releases
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      # prep the environment
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.407"
      # - uses: crazy-max/ghaction-chocolatey@v1
      #   with:
      #     args: install innosetup

      # build and test the code
      - run: dotnet build
      - run: dotnet test

      # publish and archive the different executables
      - name: Build executables
        run: ./BuildScripts/BuildAll.ps1

      # publish releases
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Releases/win-x64-slim.zip
            Releases/win-x64-selfcontained.zip
            Releases/win-arm64-slim.zip
            Releases/win-arm64-selfcontained.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
