name: Unit Testing
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # prep the environment
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.201"

      # build and test the code
      - run: dotnet build
      - run: dotnet test
